######端口
server:
  port: 8187
  ##context-path: /springboot/shiro

######数据源###
spring:
  datasource:
    url: jdbc:mysql://192.168.1.117:3306/zhaojw_master
    driver-class-name: com.mysql.jdbc.Driver
    username: fzg
    password: unreal

######mybatis的配置
mybatis.type-aliases-package: com.springboot.shiro.entity
mybatis.mapper-locations: classpath:mybatis/*.xml


####thymelea模板
thymeleaf:
       cache: false
       mode: LEGACYHTML5